# Déclaration des micro-services pour la pile
services:
  nginx:
    container_name: nginx # Conteneur du serveur Web
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./public:/var/www/html
      - ./vue:/var/www/vue
    working_dir: /var/www
  php:
    container_name: php # Conteneur du serveur php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./config:/var/www/config
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./vue:/var/www/vue
    working_dir: /var/www/html
  mysql:
    image: mysql:8.1
    container_name: mysql # Conteneur mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: helloworld
      MYSQL_USER: helloworld
      MYSQL_PASSWORD: 'helloworld'
    ports:
      - "3309:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma # Conteneur PHPMyAdmin (Outil de gestion graphique pour Mysql ou MariaDB)
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8888:80
  mongo:
    image: mongo:7.0.8
    container_name: mongo # Conteneur MongoDB
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb/db:/data/db
      - ./database/mongodb/dev.archive:/Databases/dev.archive
      - ./database/mongodb/production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: mexpress # Conteneur Mongo-Express (Outil de gestion graphique pour MongoDB)
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8181:8081"